### ISSUE TITLE
[Feature Request] Allow cookie expiration to be adjusted after first render

### ISSUE THREAD

**Issue by joeyparis** [harrysolovay/persistence-hooks#5]
Currently, `useStateAndCookie` won't update the expiration time if it is changed after the first render. This makes it difficult to have a flexible expiration time depending on a users choice (e.g. remind me tomorrow vs remind me next week). Technically we could use two separate instances of `useStateAndCookie` with the same key, but I don't know how I feel about two methods affecting the same cookie value.

My proposition would be to add a 3rd return argument in `useStateAndPersistence` called `setOptions`. Does this sound like a good approach and is it worth my time doing?

**Comment by harrysolovay** [comment]
Hi @joeyparis –– to be quite honest, I can't spend time on this repo. Would you like to be a maintainer, and add features to it?

**Comment by joeyparis** [comment]
Hi @harrysolovay, I'd be more than happy to do that! It would definitely be a small side thing for me, but I can certainly be a maintainer when I can be!

**Comment by joeyparis** [comment]
This can be accomplished with `useStateAndCookie` hook as it is now by utilizing `useEffect` for any time the expiration time changes.

e.g.
```
const [expiration_time, setExpirationTime] = useState(1)
const [value, setValue] = useStateAndCookie("value", "key", { days: expiration_time})

useEffect(() => {
    setValue(value)
}, [expiration_time])
```
